### ISSUE TITLE
Featured image displayed different with page vs. post

### ISSUE THREAD

**Issue by meulie** [AlxMedia/hueman#132]
a page with the same image as featured image, and as image within the page: https://evert.meulie.net/various/all-james-bond-movies/
a post with the same image as featured image, and as image within the post: https://evert.meulie.net/2015/03/22/oneplus-one-affordable-highend-phone/
 
Is there a reason for this? Did I misconfigure something?

**Comment by keunes** [comment]
Dunno why they're different, they're the same on my page and post (both follow the set-up of your page, but then you seem to have the sub-heading laid over the image). But then again I may have made changes in my child theme that I don't remember.
Maybe it's also to do with image quality? (the feature image on the blog is really small, maybe the theme is so smart not to spread it out over the full width?)
Maybe it's because of the post type? (my posts are standard of the 'image' type, whilst the other post types don't seem to have an image at all)

**Comment by AlxMedia** [comment]
Featured image for page: http://demo.alxmedia.se/hueman/demo/layouts/default/
Featured image for post: http://demo.alxmedia.se/hueman/2013/10/learning-more-about-macaws-in-the-amazon-jungle/

They were made like that intentionally.
