### ISSUE TITLE
Old Mobile menu : header image not working properly in mobile

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#443]
Hi,

Please refer to the following thread.
https://wordpress.org/support/topic/new-menus-problems/

Header image does not show up properly when using the following option.

Appearance -> Customize -> Header Design -> Header Menus
Find the setting -> Select the menu(s) to use for mobile devices
Select -> Topbar and header menus, logo centered

I made a test using the default header image that comes with the theme.
This is how it looks. It only shows a thin line and not the whole header image.
http://i.imgur.com/UHhndgi.png

Thank you

**Comment by ghost** [comment]
OK Thank you for reporting the problem !
![uhhndgi](https://cloud.githubusercontent.com/assets/3038156/24849090/64c007d0-1dca-11e7-9d8d-00e80c29412c.png)

**Comment by BLBNewDawn** [comment]
Hi,

What is the status on this MASSIVE bug?

The theme is pretty useless without a working menu on mobile phones!

I've tried pretty much any combinations possible and none are working to have a functioning menu on mobile...

So please fix this asap! Otherwise I will have to chuck this great theme that I've used for a couple of years. Very disappointed...

Ben
