### ISSUE TITLE
Event Calendar visual problem on date picker

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#454]
> I am setting up a new WordPress site for a client. The Hueman is well suited for their needs. After reviewing a lot of calendar plugins The Event Calendar with Event Tickets fits their needs well. I installed both free versions. (They will need the pro version of Hueman and The Event Calendar when we go live).
> 
> Everything works well except that the date picker calendars overlap and are not usable.
> 
> I did a full compatibility test and found that the problem seems to be in using The Event Calendar with the Hueman theme.
> 
> To be sure I was correct, I did a clean test install of WordPress, Installed The Event Calendar using the Twenty Seventeen theme
> 
> and the date pickers worked fine. I installed and activated the Hueman theme and date pickers once again were overlapped.
> 
> Is there any way to correct this or do I just need to select a different products. (I am also looking at different themes, but my client has already accepted Hueman.)
> 
> This is what it looks like: http://i.imgur.com/oYFpACy.jpg
> 
> I am using Chrome on Windows 10.

**Comment by ghost** [comment]
Hi @eri-trabiccolo, no emergency, this can wait next Monday.

**Comment by eri-trabiccolo** [comment]
Hi @Nikeo 
looks like a conflict with the datepicker embedded in optiontree.
Maybe, since hueman doesn't use the datepicker at all, we can consider to:
a) don't enqueue ot-datepicker resources (js standalone file)
b) remove all the references to the ot-datepicker from the od-admin(-rtl).css (ot-datepicker css rule are merged into the ot-admin css file)

Let me know if you agree and I'll push a PR tomorrow ;)

**Comment by ghost** [comment]
yep this sound good.

**Comment by eri-trabiccolo** [comment]
Merged in dev?

**Comment by ghost** [comment]
oops nope
reopened !

**Comment by ghost** [comment]
'dad
