### ISSUE TITLE
Optionally disable cropped thumbnails in grids ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#691]
> I am building a new site and have switched to the Hueman theme (free for now, but will buy Pro if it works out). The featured images I am using for posts are things like book and report covers. I really don't want them cropped into squares for thumbnails used in the archive lists. The posts I created before switching to the Hueman theme show the thumbnails correctly in archive lists, but the ones created while using the Hueman theme are cropped. Is there a way to display the full covers rather than the cropped ones? Maybe some extra CSS or a code snippet? A child theme? Does the Pro version allow this to be adjusted? Thanks.

- Is this only a consequence of our add_image_sizes ?
- Is this also related to image centering ?
- Is this also related to the responsive image ?

@eri-trabiccolo can you take the time to try various type of original image dimensions ( square, rectangle high, rectable long) and propose a solution to solve this problem ?

- Can we fix this simply with the existing options ?
- Do we need a new options like "Use original images in post lists".
- Something else ?

Thanks

**Comment by eri-trabiccolo** [comment]
> Is this only a consequence of our add_image_sizes ?

As far as I can see the image sizes defined by Hueman are cropped by default, except for the masonry one (pro) which is not cropped.
So, yeah the cropping is about Hueman.
Isn't that a design choice?

> Is this also related to image centering ?

Hueman doesn't use the js centering. Hueman-Pro does, but only for the header slider. (as far as I remember and I can see).

> Is this also related to the responsive image ?

Cropping? No. Responsive images are different image sizes of a given one that always respect its aspect ratio.

> @eri-trabiccolo can you take the time to try various type of original image dimensions ( square, rectangle high, rectable long) and propose a solution to solve this problem ?

Not sure what should I try, since the crop happens by default... In this case the only way to use original image sizes, without "loose" part of them is:
1) set featured image with the same aspect ratio of the Hueman grid thumbnail
2) use original images with dimension smaller than the Hueman grid thumbnail (which means that WordPress will not create the "thumb" image size at all, as it doesn't up-scale), but I'm not sure which image thumb will show then as fall-back, I think it will use the original, but have to check the code.

> Can we fix this simply with the existing options ?

I don't think so, unless you mean that from now on the image sizes Hueman creates will not be cropped by default. But that's a design choice so a new design choice must be done :D

> Do we need a new options like "Use original images in post lists".

Mmm, yeah, can make sense, but it should be more granular (for the different lists of posts) I think. 
Also: do we still then need to create image sizes that the user didn't want to use?

> Something else ?

See above about the need to create image sizes a user doesn't want to use.
And, maybe:
a) allow some settings about the image sizes creation (width, height, cropping), whether it should be created or not?
b) choose which image size among the available ones should be used in each context (grid, classic list, masonry, etc... )
Have to think about this.

Anyway I think there are plugins that allow the image sizes generation handling. E.g. this one:
https://wordpress.org/plugins/simple-image-sizes/
which basically should do the point a) above.

In any case:
1) Image sizes can be overridden in the child-theme, what you need is to add the same image size "after" the parent theme addition, e.g.:
```php
add_action( 'after_setup_theme', 'child_image_size', 100 );
function child_image_size() {
	add_image_size( 'thumb-medium', 100, 100, false );
}
```
There are a lot of things that can be done only with a child-theme, or with custom CSS and so on. Do we really want these kind of options? :)

2) Hueman templates can be overridden in the child theme, see: content.php where Hueman instructs about the thumbnail size to get.

**Comment by ghost** [comment]
### spec

1. add an option in the customizer, in the relevant group, to disable the use of our specific image sizes in post list context. Both in Free and Pro
2. recommend way to implement in front : use a filter for the size.

**Comment by eri-trabiccolo** [comment]
Can you confirm that for "grids" we are actually also including the standard post list? https://demo-hueman.presscustomizr.com/tag/standard-list/

And that also the content-featured should follow this despite featured posts are displayed in a carousel or not.

**Comment by ghost** [comment]
yes
and yes

**Comment by eri-trabiccolo** [comment]
Honestly I'm not sure this should be applied to the masonry too with usual theme settings.
Basically the masonry image size only forces the width (and doesn't crop), meaning that the original aspect ratio is preserved, and the article width is, at most, pretty much similar to the masonry image size width.
Of course this (article width) can increase if a bigger custom website max-width is set.
So I decided apply the "original image size" setting to the masonry grid too.

**Comment by ghost** [comment]
So you've excluded the masonry from the treatment or not ? not sure I got your point.
In any case, do what you think makes the most sense from a functional / design standpoint.

**Comment by eri-trabiccolo** [comment]
This is an opinion:
> Honestly I'm not sure this should be applied to the masonry too with usual theme settings.
> Basically the masonry image size only forces the width (and doesn't crop), meaning that the original aspect ratio is preserved, and the article width is, at most, pretty much similar to the masonry image size width.
> Of course this (article width) can increase if a bigger custom website max-width is set.

Means:
With the exception of a bigger custom website max-width set, using the original image size in the masonry grid will only result in a possible performance decrease, for what I explained before. Example:

Masonry grid image size is: 520, 9999, no crop

- User have a featured image of 1200px x 768px;
- Masonry min col is 2 (not the most used)-> with standard website width (1380px) the article image wrapper width will be: 645px (in large desktops).

Now:
- Without the new option enabled an image with width of 520px and an height "free" (keeping the original aspect ratio) will be loaded. An image with width of 520px will still look pretty fine if stretched to 645px.
- With the new option enabled an image with width of 1200px will be loaded for something that at most will display it at 645px width. (performance decrease)

Of course if the website width (which is a customizable value) goes to say 1700px, the image will be displayed at maximum 805px
- Without the new option enabled an image with width of 520px and an height "free" (keeping the original aspect ratio) will be loaded. An image with width of 520px might not look pretty fine if stretched to 805px (it depends on the image quality, the browser, the screen, etc.).
- With the new option enabled an image with width of 1200px will be loaded for something that at most will display it at 805px, but in this case the image will look better.

Those are my considerations.


This is what I did:
> Of course this (article width) can increase if a bigger custom website max-width is set.
> So I decided apply the "original image size" setting to the masonry grid too.

Meaning that this new option "Use original blog posts featured image size" is applied to all the lists of posts (masonry included).

Why?
Because otherwise I think we need to add at least another option specific for the masonry list of posts, or explain to the users why we excluded the masonry from this treatment, and what would be the solution to apply it to the masonry too? => using code or plugin: which means "back to square one".

And actually the same should be done for the `standard list of posts`, for performance reasons, for which, the maximum thumbnail wrapper width is set to 200px with CSS (but in this case the new option will introduce the undoubted advantage of not having cropped images, which was the main goal here).

_In any case, do what you think makes the most sense from a functional / design standpoint._

From a strict design standpoint, since the image sizes are a design choice, I wouldn't do anything. :) 

From a functional standpoint what we introduce here is something that is good in some cases, e.g. the user above will probably appreciate it, but cannot be defined as a real functional improvement: whit our solution (use original image sizes) what you gain without cropping for some theme image sizes (which is only a side effect of not using theme image sizes) you might lose in performances and design.

A real functional improvement would have been:
1) Allow real theme image sizes manipulation
2) Allow adding new image sizes
3) Allow "granular" (for each list of posts, featured post, at least) thumb size choice (think about the nimble img size picker).

1) and 2) could be done with the plugin aforementioned (assuming it works as expected).

Clearly 1)2)3) would be a pretty advanced function (that to me can be a pro feature), and of course something that need a little bit of time to implement + increase the "misconfiguration" problems, and still "design" issues ( but at least they can be controlled and would be a total up to the user).

So, considering all this, my _design/functional/implementation cost/support cost_ compromise choice is to stick to the initial decision (_decisions not choices_ pattern):
This new option will apply to all the list of posts, which, for a normal theme usage, will be always the same site wide.

(Hope I've been more clear :D)
