### ISSUE TITLE
WP 5.0 compatibility tests and patches

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#719]
Following the [bug discovered with Nimble](https://github.com/presscustomizr/nimble-builder/issues/225), we need to 
1. make sure there's no other problems with Hueman free and pro
2. add this compatibility patch
```php
// WP 5.0.0 compat
// @see https://core.trac.wordpress.org/ticket/45292
if ( false !== has_filter( 'content_save_pre', 'wp_targeted_link_rel' ) ) { 
 remove_filter( 'content_save_pre', 'wp_targeted_link_rel' ); 
}
```

**Comment by eri-trabiccolo** [comment]
In the free Hueman version we allow html in the footer credits, so potentially there could be a target="blank" there.
I run a simple test:
1) Put a link with target="_blank" in the footer credits input
2) Updating to WP 5.0 (nightly build)
3) Changed something in the customizer and published -> no problem, the link stays as it was (different changeset)
4) Changed the text of the link of the point 1) plus made some other change -> no change has been taken into account (since the changeset has been corrupted)

So potentially we can have this problem, rare and not disruptive...

**Comment by ghost** [comment]
Yes, this is the exact scenario.
The settings potentially containing a link with a target attribute needs to be modified to make the bug happen.
It's rare yes, but the problem is that it can be a real pain to debug if not fixed because no error displayed anywhere.

**Comment by eri-trabiccolo** [comment]
> It's rare yes, but the problem is that it can be a real pain to debug if not fixed because no error displayed anywhere.

Yes exactly.
