### ISSUE TITLE
update font awesome to 5.5 everywhere : themes, czr fmk

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#727]
http://presscustomizr.com/release-note-for-hueman-pro-v1-1-6-and-hueman-free-v3-4-9/

> Can I help update the version of Font Awesome? I see that HUEMAN PRO 1.31 is still 5.0.4, the latest version of font awesome free is 5.5, many new icons are missing.

**Comment by ghost** [comment]
While doing it, let's store the procedure for each theme/plugin in a .txt file which will become our Font_Awesome_update_process

**Comment by eri-trabiccolo** [comment]
I'm compiling the txt.
how do we want to share it?

**Comment by ghost** [comment]
as a comment here would be good.
I'll create a process repo later

**Comment by eri-trabiccolo** [comment]
there you go:

1) From https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself download the font awesome free for web package
2) Unpack it
[before copying always make sure we remove the previous fa files so that we don't
retain not used anymore files]
3) from hueman/assets/front/ remove the directoriy "webfonts" (it only contains fa fonts)]
4) from hueman/assets/front/css remove the files: "dev-font-awesome.css" and "font-awesome.min.css"
5) from fontawesome/ copy the "webfonts" directory into hueman/assets/front/
6) from fontawesome/css copy the file "all.css" into hueman/assets/front/css and rename it as "dev-font-awesome.css"
7) add a query string version, see:
https://github.com/presscustomizr/nimble-builder/issues/57#issuecomment-427181441
[generate min file]
8) in the hueman directory run the fa minify grunt task: "grunt cssmin:font_awesome_css"
it'll generate the "hueman/assets/front/css/font-awesome.min.css"
9) from "customizr/assets/shared/fonts/fa" remove the directory "webfonts"
10) empty the directory "customizr/assets/shared/fonts/fa/css"
11) from "hueman/assets/front/css" do:
    11a) copy the file "dev-font-awesome.css" into "customizr/assets/shared/fonts/fa/css"
        and rename it as "fontawesome-all.css"
    11b) copy the file "font-awesome.min.css" into "customizr/assets/shared/fonts/fa/css"
        and rename it as "fontawesome-all.min.css"
12) from "hueman/assets/front" copy the directory "webfonts" into "customizr/assets/shared/fonts/fa/"
13) from "nimble/assets/front/fonts" remove the directories "webfonts" and "css"
14) from "customizr/assets/shared/fonts/fa/" copy the directories "webfonts" and "css" into "nimble/assets/front/fonts"
15) from "czr-base-fmk/assets/fonts" remove the directories "webfonts" and "css"
16) from "customizr/assets/shared/fonts/fa/" copy the directories "webfonts" and "css" into "czr-base-fmk/assets/fonts"
17) run the nimble build tasks that will copy "czr-base-fmk" across other projects
18) re-generate the nimble FontAwesome icon list see:
 https://github.com/presscustomizr/nimble-builder/issues/57#issue-337904010
19) update transient name in https://github.com/presscustomizr/nimble-builder/blob/v1.3.2/inc/sektions/_customizer_dev_php/input_tmpl/3_0_71_sek_input_tmpl_fa_icon_picker.php#L42
method sek_retrieve_decoded_font_awesome_icons()

(tip for testing: in 5.5.0 think-peaks icon has been added)

**Comment by ghost** [comment]
perfect thank you
