### ISSUE TITLE
google recaptcha v3 icon issue

### ISSUE THREAD

**Issue by hosseinfarnia** [AlxMedia/hueman#745]
Hi,
google recaptcha version 3 icon goes behind some parts of the theme. I don't know what causes this issue, But I think it is related to this theme. you can see the recording below to understand what I say:
https://screencast-o-matic.com/watch/cqVFbG3qwn
you can also test recaptcha v3 with contact form 7 to reproduce it.
maybe the costomizr theme has the same issue, but I haven't test it yet.

**Comment by eri-trabiccolo** [comment]
Hi there,
thanks for reporting this.

That raises a "conflict of competences", because it should be up to the recaptcha style, or at least of the plugin which embeds it, to at least try to make sure the icon is visible, the same way they make sure the icon is "floating".

But thanks for reporting this, we'll consider to force its z-index to an opportune value :)

**Comment by hosseinfarnia** [comment]
Hi
I've tested with other plugins which use recaptcha v3 and they have the same issue with hueman theme.
But I prefer to hide it with this code:
```
.grecaptcha-badge {
    display: none;
}
```
In google recaptcha documentation has been written that it is allowed to hide this logo without any problem.
Thanks

**Comment by eri-trabiccolo** [comment]
Hi Hossein,
thanks.

Yes, I see, as I said, in the first place the recaptcha style itself should take care of setting a z-index to it, exactly like it sets its fixed position, can also set the `z-index`.
If the google recaptcha javascript doesn't do that (and it doesn't), maybe the plugin that uses it can do that, if it doesn't (and it doesn't) would be probably up to us to decide what to do :D
