### ISSUE TITLE
potential regression introduced when fixing infinite scroll issue

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#766]
regression introduced in https://github.com/presscustomizr/hueman/pull/755
The effect being : https://wordpress.org/support/topic/featured-posts-in-header-not-working-anymore-since-update/#post-11193897

**Comment by ghost** [comment]
@eri-trabiccolo in your column :)

**Comment by eri-trabiccolo** [comment]
CPT + custom code involved as far as I can see.
So another custom code might also fix it ahahah
Though I'm not totally positive this issue has been introduced while fixing.the infinite scroll bug, because the added code applies only when in the callback of the infinite filter hook...
I'm actually not even sure the whole new feature (blog.filter) is causing the featured posts issue as it acts only on the main query (or at least is designed to do so).
Will investigate tomorrow - I might be wrong, I'm traveling right now. :)

**Comment by eri-trabiccolo** [comment]
I leave my thoughts here (while I investigate into this).

This is the code the user says the former developer "probably" used to show CPT in the featured posts slider:

```
function custom_request($qs) {
	if(isset($qs['tag']) || isset($qs['category_name'])) {
		$qs = array_merge($qs, array('post_type' => array('post', 'page', 'rezept', 'foodlexikon', 'product')));
	}
	return $qs;
}
add_filter('request', 'custom_request');
```

Which, as far as I read, and tested (to be sure), acts before the main query SQL is executed, not on custom queries.
https://codex.wordpress.org/Plugin_API/Filter_Reference/request

And, again as far as I can read, it should basically "extend" the the category and tag archive pages to show also CPTs, e.g. a 'rezept' CPT with category_name "A" will be shown in the category archive page "A" along with posts with category_name "A".

**Comment by ghost** [comment]
OK. Thanks.
If needed, don't hesitate to take over in the topic and reply directly to gfra in this https://wordpress.org/support/topic/featured-posts-in-header-not-working-anymore-since-update/#post-11193897

**Comment by eri-trabiccolo** [comment]
Yeah,
because I have to know what's the custom code that site is using to show the CPT in the featured posts "section", since by default only standard posts are shown there, and the theme provides no filter nor a specific option to alter this behavior.
Basically here, as far as I can tell, we're trying to fix a conflict with a custom code :D

**Comment by ghost** [comment]
Let's chat quickly in 2 minutes?

**Comment by ghost** [comment]
Let's close this for now then.
