### ISSUE TITLE
Sidebar => add an option to set an order on mobile devices

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#779]
related to #406

https://secure.helpscout.net/conversation/799116480/175101?folderId=607547
> I need to show the primary sidebar before the content (posts) in the mobile view. We sell tickets for dance events and want to show that first to the mobile user. Can something be adjusted or modiefied to enable the view of the primary sidebar before the standard content of Wordpress?

@eri-trabiccolo I put it in our _to be discussed_ list

**Comment by eri-trabiccolo** [comment]
requested here too:
https://wordpress.org/support/topic/mobile-version-block-display-order/

**Comment by ghost** [comment]
OK @eri-trabiccolo I put it in your colUMN

**Comment by eri-trabiccolo** [comment]
I would avoid js solutions that, as we know, can create problems with iframes (see Customizr classic style), and rather go with a CSS3 based solution (see how we use the `order` in Customizr modern style), if we can :D.

**Comment by ghost** [comment]
Yes no js. If not possible with CSS only, then we won't do it.

**Comment by eri-trabiccolo** [comment]
I was on this and turned out to be pretty easy to implement with flex.
I need some specs here.
1) order on "mobile" devices: 
Since the order of the blocks (sidebars and content) changes only for window's width < 480px, I think we're talking about small devices, so tablet viewports are excluded. I'm asking this because in the first comment to this issue it's stated this is related to #406 which is pretty specific for tablets...

2) This order option can just be a checkbox that says something like: "In small devices always display the Primary sidebar before the content column"?
To keep things simple, avoiding users messing up with two sidebars + content order etc etc.

**Comment by ghost** [comment]
OK I'm just back home now. I'll reply tomorrow thanks

**Comment by ghost** [comment]
1. Yes this applies when the blocks are re-organized only. Otherwise it would imply that we need to change the current breakpoint which is out of the scope of this PR
2. yes, as simple, short wording, and straight forward as possible.

**Comment by ghost** [comment]
thanks

**Comment by eri-trabiccolo** [comment]
1. Yeah, thanks, that's what I thought, no relationship between the meanings of "mobile" in this issue and the #406. Thanks for clarifying.
2. Yes, trying to use the current Hueman wording to be as much understandable as possible.

**Comment by eri-trabiccolo** [comment]
Did it.
Let me know if you don't like it...

I've tested it with the major browsers (chrome/firefox/opera/safari) on a mac...
and with my android smartphone.
