### ISSUE TITLE
Post list => featured post thumbnail definition => explore solution to use the relevant thumbnail size on desktops

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#799]
https://secure.helpscout.net/conversation/869503744/217600/?folderId=607547

**Comment by ghost** [comment]
To be tested with a featured image.
Possible bug source : plugin conflict

**Comment by eri-trabiccolo** [comment]
I cannot reproduce the very issue the user is reporting on the user website to be honest.
What I can see though is that images are a little bit fuzzy due to a CSS property (perspective) - I'm on it -  that recently has proved to be "buggy", for other reasons, in chrome (see: https://github.com/presscustomizr/tc-unlimited-featured-pages/commit/383240efaf708a71215703a7ed35c03e54653ca1).

From our standpoint, as you said, we rely on the wp responsive images implementation, and at the end the actual image of the srcset that will be chosen is up to the browser. :/.

**Comment by ghost** [comment]
ok. thanks
