### ISSUE TITLE
Button broken on Apple mobile devices

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#813]
The button of a plugin is styled differently on desktop and Apple mobile devices.

reported here : https://secure.helpscout.net/conversation/909276277/218097/?folderId=607547

### Desktop ( good )
![2019-07-23_09-53-32](https://user-images.githubusercontent.com/3038156/61693492-f2cb7900-ad2f-11e9-86d0-fc3df3183815.jpg)

### Apple device ( wrong )
![2019-07-23_09-53-39](https://user-images.githubusercontent.com/3038156/61693496-f3fca600-ad2f-11e9-929c-5416f56583f2.jpg)

This does not occur on other themes. ( tested with Customizr in same conditions , style not broken )

## CAN WE REPRODUCE ?
The first thing is to do is to try reproduce the issue.
With the plugin  MailOptin - Lite (version 1.2.18.0) + Hueman Pro / Hueman

### IF REPRODUCTIBLE :
It means that Hueman theme probably has some Apple specific CSS rules for input type="submit"

`
<input id="kdAfodEXVa_sidebar_submit_button" class="mo-optin-form-submit-button gridgum_submit_button" style="background: #bf5111;color: #ffffff;height: auto;text-shadow: none;font-family: Poppins, Helvetica, Arial, sans-serif;" type="submit" value="Subscribe Now">`

**Comment by eri-trabiccolo** [comment]
Took me a lot of time to understand this.
The problem is not what CSS Hueman has that causes that, but what CSS Hueman (and the plugin itself) **doesn't** have that causes this.
In Customizr and a bunch of other themes, like Twenty Seventeen the issue doesn't occurr because of something like this (took from Twenty Seventeen):
```css
button,
html [type="button"],
[type="reset"],
[type="submit"] {
	-webkit-appearance: button;
}
```

Hueman has some sort of CSS, but it applies it only to those elements that are descendants of a `.themeform` element:
https://github.com/presscustomizr/hueman/blob/v3.4.26/assets/front/css/_parts/0_1_base_styles.css#L121-L124

We should extend that to the `input['submit']` too.

**Comment by eri-trabiccolo** [comment]
hopefully it won't have any drawback.

**Comment by ghost** [comment]
cool !
