### ISSUE TITLE
Super form pop up not working

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#823]
https://secure.helpscout.net/conversation/949513621/218534?folderId=607547

Able to reproduce the bug. Not able to understand the problem.

**Comment by eri-trabiccolo** [comment]
I haven't dug too much into this, but I though it could have been because of the fact that hueman adds the `do_shortcode` callback to the `widget_text` filter hook.  
The plugin adds it too at priority 100.
In any case, since 4.8.0 (I think), WP removes the first `do_shortcode` callback added to `widget_text` because the core itself adds it to a later filter hook `widget_text_content` (this exists since 4.8.0).
So if hueman adds its filter callback the core will remove it, the plugin one will stay there and the `do_shortcode` callback will run twice, one at `widget_text`|100 and the second time at `widget_text_content` (because of the wp core).
So probably the plugin's shortcode callback is not idempotent and when ran twice it breaks something (this means that they would have a similar issue with any other 3rd party code that does what hueman does).

Solution?
Let's make "pretty sure" we don't add the `do_shortcode` callback if wp>=4.8.0 OR, anyways, the `do_shortcode` filter callback has already been added to the `widget_text` filter hook.

**Comment by ghost** [comment]
Impressed.
