### ISSUE TITLE
Header image stretched after update to 3.5.3

### ISSUE THREAD

**Issue by celticalliance** [AlxMedia/hueman#876]
We are using Hueman Free.

After the update to 3.5.3 our header image is stretched over the entire width of the page, making the image look different and much wider than before.

I have looked in the customization section and cannot find any option to rectify this. Please advise what I have to do next.

**Comment by ghost** [comment]
Hello,
Can you open a new topic in the support forum about the header image ? 

https://wordpress.org/support/theme/hueman/
This is where our team collects the questions and potential issues about Hueman.
The forum is used by many users to find answers to their questions, including this one.

When you'll open the forum topic : 
- Please make sure to share your site URL when possible, so that we can see the issue and run some tests on your site.
- Include your system infos when creating your post. You’ll find them under Dashboard > Themes > About Hueman

Looking forward to read you on the forum.
Thank you

**Comment by celticalliance** [comment]
I don't have an account over there. This issue did not occur before this version and as I said I do not see an option anywhere to disable the feature where it makes the image larger.

When looking at the element info from my browser I see the image is stretched to fill the width of the website. I can change that to a smaller value, but it makes the website look really weird.

FYI, we are using a child theme with no changes made whatsoever to any CSS or anything. All I would like to know is how I can make it so that the theme does not automatically stretch the image, because that is what is happening.

**Comment by ghost** [comment]
fixed in #883
