### ISSUE TITLE
Adjustable Sidebar Widths

### ISSUE THREAD

**Issue by taylorjameswalker** [AlxMedia/hueman#92]
Could you please implement more than the current 2 options for sidebar widths? I'd actually just like to swap them (narrow on the left, wide on the right). I accomplished this with CSS but it breaks responsiveness and some other things. Any feedback would be much appreciated. 

Thank you for your time and consideration!

**Comment by AlxMedia** [comment]
Hi there!

There is so much CSS and stuff going on in order for the sidebars to work with all 5 layout modes, that adding more is a headache. Mostly because each sidebar width uses a background image to expand downward. So it can't really be done easily.

Thanks for the suggestion though! I know the sidebars are a pain to edit, but there are some threads on the support forums.
